apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ required "A valid .Values.namespace is required!" .Values.namespace }}
  labels:
    {{- include "nsvalidator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nsvalidator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nsvalidator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ .Chart.Name }}-sa"
      imagePullSecrets:
        - name: harbor
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: WEBHOOK_SERVICE
              value: {{.Release.Name}}
            - name: WEBHOOK_NAMESPACE
              value: {{.Release.Namespace}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
          volumeMounts:
          - name: tls-cert
            mountPath: "/etc/tls"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: tls-cert
        emptyDir: {}
