apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Chart.Name }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Chart.Name }}"
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Chart.Name }}-binding"
  labels: 
    {{- include "nsprotection.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Chart.Name }}"
    namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: "{{ .Chart.Name }}"
  apiGroup: rbac.authorization.k8s.io

