apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Chart.Name }}-sa"
  namespace: {{ required "A valid .Values.namespace is required!" .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Chart.Name }}-sa-binding"
  labels: 
    {{- include "nsvalidator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Chart.Name }}-sa"
    namespace: {{ required "A valid .Values.namespace is required!" .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
