apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsprotection.fullname" . }}
  labels:
    {{- include "nsprotection.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: http
  selector: 
    {{- include "nsprotection.selectorLabels" . | nindent 4 }}
